AppointmentBookSystem/Controllers/tbl_DoctorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AppointmentBookSystem;

namespace AppointmentBookSystem.Controllers
{
    public class tbl_DoctorController : Controller
    {
        private AppointmentBookSystemEntities db = new AppointmentBookSystemEntities();
        [Authorize(Roles = "Admin,User")]
        // GET: tbl_Doctor
        public ActionResult Index()
        {
            var tbl_Doctor = db.tbl_Doctor.Include(t => t.tbl_specialization);
            return View(db.tbl_Doctor.ToList());
        }
        [HttpGet]
        public async Task<ActionResult> Index(String doctorSearch)
        {
            ViewData["GetDoctorDetails"] = doctorSearch;
            var doctorQuery=from x in db.tbl_Doctor select x;
            if(!String.IsNullOrEmpty(doctorSearch))
            {
                doctorQuery = doctorQuery.Where(x => x.Doctor_Name.Contains(doctorSearch) || x.Doctor_Username.Contains(doctorSearch));

            }
            return View(await doctorQuery.AsNoTracking().ToListAsync());

        }
        // GET: tbl_Doctor/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Doctor tbl_Doctor = db.tbl_Doctor.Find(id);
            if (tbl_Doctor == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Doctor);
        }
        [Authorize(Roles = "Admin")]
        // GET: tbl_Doctor/Create
        public ActionResult Create()
        {
            ViewBag.Doctor_Specialization_Id = new SelectList(db.tbl_Specialization, "Specialization_Id", "Specialization_Name");
            
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: tbl_Doctor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Doctor_Id,Doctor_Name,Doctor_Username,Doctor_Password,Doctor_Gender,Doctor_Phone,Doctor_Address,Doctor_IsAvailable,Doctor_Specialization_Id")] tbl_Doctor tbl_Doctor)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Doctor.Add(tbl_Doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Doctor_Specialization_Id = new SelectList(db.tbl_Specialization, "Specialization_Id", "Specialization_Name",tbl_Doctor.Doctor_Specialization_Id);

            return View(tbl_Doctor);
        }
        [Authorize(Roles = "Admin")]
        // GET: tbl_Doctor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Doctor tbl_Doctor = db.tbl_Doctor.Find(id);
            if (tbl_Doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.Doctor_Specialization_Id = new SelectList(db.tbl_Specialization, "Specialization_Id", "Specialization_Name", tbl_Doctor.Doctor_Specialization_Id);

            return View(tbl_Doctor);
        }

        // POST: tbl_Doctor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Doctor_Id,Doctor_Name,Doctor_Username,Doctor_Password,Doctor_Gender,Doctor_Phone,Doctor_Address,Doctor_IsAvailable,Doctor_Specialization_Id")] tbl_Doctor tbl_Doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Doctor_Specialization_Id = new SelectList(db.tbl_Specialization, "Specialization_Id", "Specialization_Name", tbl_Doctor.Doctor_Specialization_Id);

            return View(tbl_Doctor);
        }
        [Authorize(Roles = "Admin")]
        // GET: tbl_Doctor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Doctor tbl_Doctor = db.tbl_Doctor.Find(id);
            if (tbl_Doctor == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Doctor);
        }

        // POST: tbl_Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Doctor tbl_Doctor = db.tbl_Doctor.Find(id);
            db.tbl_Doctor.Remove(tbl_Doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppointmentBookSystem/Controllers/tbl_PatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppointmentBookSystem;

namespace AppointmentBookSystem.Controllers
{
    public class tbl_PatientController : Controller
    {
        private AppointmentBookSystemEntities db = new AppointmentBookSystemEntities();

        // GET: tbl_Patient
        [Authorize(Roles ="Admin,Doctor")]
        public ActionResult Index()
        {
            return View(db.tbl_Patient.ToList());
        }

        // GET: tbl_Patient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Patient tbl_Patient = db.tbl_Patient.Find(id);
            if (tbl_Patient == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Patient);
        }

        // GET: tbl_Patient/Create
        [Authorize(Roles = "Admin,User")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: tbl_Patient/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public ActionResult Create([Bind(Include = "Patient_Id,Patient_Name,Patient_Username,Patient_Password,Patient_Gender,Patient_DOB,Patient_Phone,Patient_Address,Patient_City,Patient_Height,Patient_Weight")] tbl_Patient tbl_Patient)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Patient.Add(tbl_Patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Patient);
        }

        // GET: tbl_Patient/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Patient tbl_Patient = db.tbl_Patient.Find(id);
            if (tbl_Patient == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Patient);
        }

        // POST: tbl_Patient/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Patient_Id,Patient_Name,Patient_Username,Patient_Password,Patient_Gender,Patient_DOB,Patient_Phone,Patient_Address,Patient_City,Patient_Height,Patient_Weight")] tbl_Patient tbl_Patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Patient);
        }

        // GET: tbl_Patient/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Patient tbl_Patient = db.tbl_Patient.Find(id);
            if (tbl_Patient == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Patient);
        }

        // POST: tbl_Patient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Patient tbl_Patient = db.tbl_Patient.Find(id);
            db.tbl_Patient.Remove(tbl_Patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppointmentBookSystem/Controllers/tbl_UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppointmentBookSystem;

namespace AppointmentBookSystem.Controllers
{
    public class tbl_UserController : Controller
    {
        private AppointmentBookSystemEntities db = new AppointmentBookSystemEntities();
        [Authorize(Roles = "Admin")]
        // GET: tbl_User
        public ActionResult Index()
        {
            return View(db.tbl_User.ToList());
        }

        // GET: tbl_User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_User tbl_User = db.tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // GET: tbl_User/Create
        public ActionResult Create()
        {
            ViewBag.User_Role_Id = new SelectList(db.tbl_Role, "Role_Id", "Role_Name");
            return View();
        }

        // POST: tbl_User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "User_Id,User_Username,User_Password,User_Role_Id")] tbl_User tbl_User)
        {
            if (ModelState.IsValid)
            {
                db.tbl_User.Add(tbl_User);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User_Role_Id = new SelectList(db.tbl_Role, "Role_Id", "Role_Name",tbl_User.User_Role_Id);
            return View(tbl_User);
        }

        // GET: tbl_User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_User tbl_User = db.tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            ViewBag.User_Role_Id = new SelectList(db.tbl_Role, "Role_Id", "Role_Name", tbl_User.User_Role_Id);
            return View(tbl_User);
        }

        // POST: tbl_User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "User_Id,User_Username,User_Password,User_Role_Id")] tbl_User tbl_User)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_User).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User_Role_Id = new SelectList(db.tbl_Role, "Role_Id", "Role_Name", tbl_User.User_Role_Id);
            return View(tbl_User);
        }

        // GET: tbl_User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_User tbl_User = db.tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // POST: tbl_User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_User tbl_User = db.tbl_User.Find(id);
            db.tbl_User.Remove(tbl_User);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppointmentBookSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Doctor Appointment Booking System", "Index", "tbl_Patient", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                @*<ul class="nav navbar-nav">*@
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Patients", "Index", "tbl_Patient")</li>
                            <li>@Html.ActionLink("Users", "Index", "tbl_User")</li>
                            <li>@Html.ActionLink("Add Doctors", "Create", "tbl_Doctor")</li>
                        }
                        if (User.IsInRole("Admin") || User.IsInRole("User"))
                        {
                            <li>@Html.ActionLink("Add Patients", "Create", "tbl_Patient")</li>
                            <li>@Html.ActionLink("Doctors", "Index", "tbl_Doctor")</li>
                            <li>@Html.ActionLink("Create Appointments", "Create", "tbl_Appointment")</li>
                            <li>@Html.ActionLink("Appointments", "Index", "tbl_Appointment")</li>
                        }
                        if (User.IsInRole("Doctor"))
                        {
                            <li>@Html.ActionLink("Patients", "Index", "tbl_Patient")</li>
                            @*<li>@Html.ActionLink("Doctors", "Index", "tbl_Doctor")</li>
                                <li>@Html.ActionLink("Create Appointments", "Create", "tbl_Appointment")</li>*@
                            <li>@Html.ActionLink("Appointments", "Index", "tbl_Appointment")</li>
                        }
                        <li><a>Welcome - @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Register", "Register", "Account")</li>
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>

                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/MyJS.js"></script>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>